// Code generated by protoc-gen-go. DO NOT EDIT.
// source: register.proto

/*
Package dkmanager is a generated protocol buffer package.

It is generated from these files:
	register.proto

It has these top-level messages:
	HostRegisterInfo
	RegisterResult
	HostReport
	ReportStatus
*/
package dkmanager

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_ONLINE  Status = 0
	Status_OFFLINE Status = 1
	Status_BROKEN  Status = 2
)

var Status_name = map[int32]string{
	0: "ONLINE",
	1: "OFFLINE",
	2: "BROKEN",
}
var Status_value = map[string]int32{
	"ONLINE":  0,
	"OFFLINE": 1,
	"BROKEN":  2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HostRegisterInfo struct {
	HostName string `protobuf:"bytes,1,opt,name=HostName,json=hostName" json:"HostName,omitempty"`
	HostAddr string `protobuf:"bytes,2,opt,name=HostAddr,json=hostAddr" json:"HostAddr,omitempty"`
	HostPort int32  `protobuf:"varint,3,opt,name=HostPort,json=hostPort" json:"HostPort,omitempty"`
}

func (m *HostRegisterInfo) Reset()                    { *m = HostRegisterInfo{} }
func (m *HostRegisterInfo) String() string            { return proto.CompactTextString(m) }
func (*HostRegisterInfo) ProtoMessage()               {}
func (*HostRegisterInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HostRegisterInfo) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *HostRegisterInfo) GetHostAddr() string {
	if m != nil {
		return m.HostAddr
	}
	return ""
}

func (m *HostRegisterInfo) GetHostPort() int32 {
	if m != nil {
		return m.HostPort
	}
	return 0
}

type RegisterResult struct {
	Result bool `protobuf:"varint,1,opt,name=Result,json=result" json:"Result,omitempty"`
}

func (m *RegisterResult) Reset()                    { *m = RegisterResult{} }
func (m *RegisterResult) String() string            { return proto.CompactTextString(m) }
func (*RegisterResult) ProtoMessage()               {}
func (*RegisterResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type HostReport struct {
	HostName   string `protobuf:"bytes,1,opt,name=HostName,json=hostName" json:"HostName,omitempty"`
	HostStatus Status `protobuf:"varint,2,opt,name=HostStatus,json=hostStatus,enum=dkmanager.Status" json:"HostStatus,omitempty"`
}

func (m *HostReport) Reset()                    { *m = HostReport{} }
func (m *HostReport) String() string            { return proto.CompactTextString(m) }
func (*HostReport) ProtoMessage()               {}
func (*HostReport) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HostReport) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *HostReport) GetHostStatus() Status {
	if m != nil {
		return m.HostStatus
	}
	return Status_ONLINE
}

type ReportStatus struct {
	Result bool `protobuf:"varint,1,opt,name=Result,json=result" json:"Result,omitempty"`
}

func (m *ReportStatus) Reset()                    { *m = ReportStatus{} }
func (m *ReportStatus) String() string            { return proto.CompactTextString(m) }
func (*ReportStatus) ProtoMessage()               {}
func (*ReportStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReportStatus) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*HostRegisterInfo)(nil), "dkmanager.HostRegisterInfo")
	proto.RegisterType((*RegisterResult)(nil), "dkmanager.RegisterResult")
	proto.RegisterType((*HostReport)(nil), "dkmanager.HostReport")
	proto.RegisterType((*ReportStatus)(nil), "dkmanager.ReportStatus")
	proto.RegisterEnum("dkmanager.Status", Status_name, Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Registry service

type RegistryClient interface {
	Register(ctx context.Context, in *HostRegisterInfo, opts ...grpc.CallOption) (*RegisterResult, error)
	ReportNodeStatus(ctx context.Context, in *HostReport, opts ...grpc.CallOption) (*ReportStatus, error)
}

type registryClient struct {
	cc *grpc.ClientConn
}

func NewRegistryClient(cc *grpc.ClientConn) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) Register(ctx context.Context, in *HostRegisterInfo, opts ...grpc.CallOption) (*RegisterResult, error) {
	out := new(RegisterResult)
	err := grpc.Invoke(ctx, "/dkmanager.Registry/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) ReportNodeStatus(ctx context.Context, in *HostReport, opts ...grpc.CallOption) (*ReportStatus, error) {
	out := new(ReportStatus)
	err := grpc.Invoke(ctx, "/dkmanager.Registry/ReportNodeStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Registry service

type RegistryServer interface {
	Register(context.Context, *HostRegisterInfo) (*RegisterResult, error)
	ReportNodeStatus(context.Context, *HostReport) (*ReportStatus, error)
}

func RegisterRegistryServer(s *grpc.Server, srv RegistryServer) {
	s.RegisterService(&_Registry_serviceDesc, srv)
}

func _Registry_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostRegisterInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dkmanager.Registry/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).Register(ctx, req.(*HostRegisterInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_ReportNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).ReportNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dkmanager.Registry/ReportNodeStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).ReportNodeStatus(ctx, req.(*HostReport))
	}
	return interceptor(ctx, in, info, handler)
}

var _Registry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dkmanager.Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Registry_Register_Handler,
		},
		{
			MethodName: "ReportNodeStatus",
			Handler:    _Registry_ReportNodeStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "register.proto",
}

func init() { proto.RegisterFile("register.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x5f, 0x4b, 0xf3, 0x30,
	0x14, 0xc6, 0x9b, 0xbd, 0xbc, 0xb1, 0x3b, 0x4a, 0xa9, 0x01, 0xb5, 0xd6, 0x9b, 0x91, 0x0b, 0x29,
	0x82, 0x05, 0xe7, 0x27, 0x50, 0xb6, 0xe1, 0x50, 0x52, 0x89, 0x97, 0x5e, 0x55, 0x9a, 0x6d, 0xa2,
	0x5b, 0xc6, 0x69, 0x76, 0xe1, 0x17, 0xf1, 0xf3, 0x4a, 0x92, 0x76, 0x7f, 0x14, 0xbd, 0x3b, 0x4f,
	0x9e, 0x87, 0x73, 0x7e, 0xe7, 0x04, 0x22, 0x54, 0xd3, 0xd7, 0xda, 0x28, 0xcc, 0x97, 0xa8, 0x8d,
	0x66, 0xdd, 0xea, 0x6d, 0x5e, 0x2e, 0xca, 0xa9, 0x42, 0x3e, 0x81, 0xf8, 0x4e, 0xd7, 0x46, 0x36,
	0x81, 0xf1, 0x62, 0xa2, 0x59, 0x0a, 0xa1, 0x7d, 0x13, 0xe5, 0x5c, 0x25, 0xa4, 0x47, 0xb2, 0xae,
	0x0c, 0x67, 0x8d, 0x6e, 0xbd, 0x9b, 0xaa, 0xc2, 0xa4, 0xb3, 0xf1, 0xac, 0x6e, 0xbd, 0x47, 0x8d,
	0x26, 0xf9, 0xd7, 0x23, 0xd9, 0x7f, 0xef, 0x59, 0xcd, 0x33, 0x88, 0xda, 0x19, 0x52, 0xd5, 0xab,
	0x77, 0xc3, 0x8e, 0x81, 0xfa, 0xca, 0xcd, 0x08, 0x25, 0x45, 0xa7, 0xf8, 0x33, 0x80, 0x27, 0x5a,
	0x6a, 0x34, 0x7f, 0xb2, 0x5c, 0xf9, 0xe4, 0x93, 0x29, 0xcd, 0xaa, 0x76, 0x34, 0x51, 0xff, 0x30,
	0x5f, 0xef, 0x96, 0x7b, 0x43, 0xc2, 0x6c, 0x1d, 0xe2, 0xe7, 0x70, 0xe0, 0x1b, 0x7b, 0xfd, 0x1b,
	0xc4, 0xc5, 0x25, 0xd0, 0x26, 0x01, 0x40, 0x0b, 0xf1, 0x30, 0x16, 0xc3, 0x38, 0x60, 0xfb, 0xb0,
	0x57, 0x8c, 0x46, 0x4e, 0x10, 0x6b, 0xdc, 0xca, 0xe2, 0x7e, 0x28, 0xe2, 0x4e, 0xff, 0x93, 0x40,
	0xe8, 0xd7, 0xc3, 0x0f, 0x36, 0x68, 0x6b, 0x85, 0xec, 0x6c, 0x0b, 0xe7, 0xfb, 0x9d, 0xd3, 0xd3,
	0x2d, 0x73, 0xf7, 0x38, 0x3c, 0x60, 0x03, 0x88, 0x3d, 0xa9, 0xd0, 0x95, 0x6a, 0x58, 0x8e, 0x7e,
	0x74, 0xb3, 0x81, 0xf4, 0x64, 0xa7, 0xcf, 0x66, 0x3b, 0x1e, 0xbc, 0x50, 0xf7, 0xe1, 0xd7, 0x5f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x36, 0xb0, 0xbd, 0x62, 0x02, 0x02, 0x00, 0x00,
}
